#!/bin/bash

# Setup script

echo "Building file structure"
mkdir site/projects
touch user/projects.yml
chmod 664 user/projects.yml

echo "---- If this next step fails, it's OK ----"
sass site/bulma/bulma.sass --style compressed > site/bulma.min.css

echo "Done!"