#!/usr/bin/env ruby

require 'socket'
require './lib/app.rb'

# Load config
config = read_YAML("config.yml")
ADDRESS =  ARGV[0] || config['address'] || 'localhost'
PORT    =  ARGV[1] || config['port']    || 3000

# Load correct server
if config['https'] == true
	require './lib/https-server.rb'
else
	require './lib/http-server.rb'
end

server = Server.new(ADDRESS, PORT)
server = server.start()

app(server)
