#!/usr/bin/env ruby

require 'socket'
require './lib/app.rb'
require './lib/http-server.rb'

# Load config
config = read_YAML("config.yml")
PORT = ARGV[0] || config['port']
ADDRESS =  config['address'] || 'localhost'

server = HTTP_Server.new(ADDRESS, PORT)
server = server.start()

app(server)
